#!/usr/bin/env python3
"""Regenerate providermeta.js from the Swift ProviderDescriptors.

The upstream CLI's `config providers --format json` only carries
{provider, displayName, enabled, defaultEnabled}; the dashboard/status
URLs and branding live in Sources/CodexBarCore/Providers/*/
*ProviderDescriptor.swift as ProviderMetadata literals. Until upstream
exposes them over the CLI (planned PR), this script extracts them
statically and emits the ESM module the extension and prefs import.

Usage (from the repo root):
    python3 linux/usagebar-gnome/tools/gen-provider-meta.py

Only string/bool/number literals are understood; a field whose value is
an expression is treated as absent. Fields are matched inside the
ProviderMetadata(...) call only, so descriptor-level `id:` duplicates
don't confuse it.
"""

import glob
import json
import os
import re
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
DESCRIPTOR_GLOB = os.path.join(
    REPO, 'Sources', 'CodexBarCore', 'Providers', '*', '*ProviderDescriptor.swift')
OUT = os.path.join(
    REPO, 'linux', 'usagebar-gnome', 'usagebar@felipearosr.github.io', 'providermeta.js')

# Feed shapes the extension's status strip can parse. statuspage is derived
# from statusPageURL; entries here override that, keyed by status-page URL so
# every provider on the page inherits the fix (incident.io pages whose
# statuspage-compat API strips component tags need their native feed).
STATUS_FEED_OVERRIDES = {
    'https://status.openai.com': {
        'kind': 'incidentio',
        'base': 'https://status.openai.com/proxy/status.openai.com'},
}

# Status-strip scopes per provider: which slices of the status page the
# strip can track. Curated — component/group names are judgment calls per
# page; the first entry is the provider's default. Providers absent here
# (or without a feed) track 'Everything'.
STATUS_SCOPES = {
    'codex': ['Codex', 'APIs', 'ChatGPT', 'Everything'],
    'claude': ['Claude Code', 'Claude API', 'claude.ai', 'Claude Console', 'Everything'],
}

STR_FIELDS = {
    'displayName': 'name',
    'dashboardURL': 'dashboard',
    'subscriptionDashboardURL': 'subscriptionDashboard',
    'statusPageURL': 'statusPage',
    'statusLinkURL': 'statusLink',
}


def metadata_block(src):
    """The argument text of the ProviderMetadata(...) call, by paren depth."""
    start = src.find('ProviderMetadata(')
    if start < 0:
        return None
    i = start + len('ProviderMetadata(')
    depth = 1
    while i < len(src) and depth:
        if src[i] == '(':
            depth += 1
        elif src[i] == ')':
            depth -= 1
        i += 1
    return src[start:i]


def str_field(block, field):
    m = re.search(rf'\b{field}:\s*"((?:[^"\\]|\\.)*)"', block)
    return m.group(1) if m else None


def color_field(src):
    m = re.search(
        r'ProviderColor\(\s*red:\s*([\d.]+(?:\s*/\s*255)?),'
        r'\s*green:\s*([\d.]+(?:\s*/\s*255)?),'
        r'\s*blue:\s*([\d.]+(?:\s*/\s*255)?)\s*\)', src)
    if not m:
        return None
    vals = []
    for raw in m.groups():
        # "0 / 255" keeps the numerator; a bare float like 0.75 is 0-1 scale.
        num = float(raw.split('/')[0])
        vals.append(int(round(num if '/' in raw else num * 255)))
    return '#{:02x}{:02x}{:02x}'.format(*(min(255, max(0, v)) for v in vals))


def parse(path):
    with open(path, encoding='utf-8') as f:
        src = f.read()
    block = metadata_block(src)
    if not block:
        return None
    pid = re.search(r'\bid:\s*\.(\w+)', block)
    if not pid:
        return None
    entry = {}
    for swift, js in STR_FIELDS.items():
        val = str_field(block, swift)
        if val:
            entry[js] = val
    color = color_field(src)
    if color:
        entry['color'] = color
    provider = pid.group(1)
    page = (entry.get('statusPage') or '').rstrip('/')
    feed = STATUS_FEED_OVERRIDES.get(page)
    if not feed and page:
        feed = {'kind': 'statuspage', 'base': page}
    if feed:
        entry['statusFeed'] = feed
        scopes = STATUS_SCOPES.get(provider)
        if scopes:
            entry['statusScopes'] = scopes
    return provider, entry


def main():
    paths = sorted(glob.glob(DESCRIPTOR_GLOB))
    if not paths:
        sys.exit(f'no descriptors found under {DESCRIPTOR_GLOB}')
    meta = {}
    for path in paths:
        parsed = parse(path)
        if not parsed:
            print(f'warning: no ProviderMetadata in {path}', file=sys.stderr)
            continue
        provider, entry = parsed
        if provider in meta:
            print(f'warning: duplicate provider {provider} from {path}', file=sys.stderr)
        meta[provider] = entry

    lines = [
        '// GENERATED by linux/usagebar-gnome/tools/gen-provider-meta.py — do not edit.',
        '// Source of truth: Sources/CodexBarCore/Providers/*/*ProviderDescriptor.swift.',
        '// Regenerate after syncing with upstream:',
        '//   python3 linux/usagebar-gnome/tools/gen-provider-meta.py',
        '',
        '/* eslint-disable */',
        f'export const PROVIDER_META = {json.dumps(meta, indent=4, ensure_ascii=False)};',
    ]
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'{len(meta)} providers -> {os.path.relpath(OUT, REPO)}')


if __name__ == '__main__':
    main()
