// GENERATED by linux/usagebar-gnome/tools/gen-provider-meta.py — do not edit.
// Source of truth: Sources/CodexBarCore/Providers/*/*ProviderDescriptor.swift.
// Regenerate after syncing with upstream:
//   python3 linux/usagebar-gnome/tools/gen-provider-meta.py

/* eslint-disable */
export const PROVIDER_META = {
    "abacus": {
        "name": "Abacus AI",
        "dashboard": "https://apps.abacus.ai/chatllm/admin/compute-points-usage",
        "color": "#38bdf8"
    },
    "alibaba": {
        "name": "Alibaba",
        "statusLink": "https://status.aliyun.com",
        "color": "#ff6a00"
    },
    "alibabatokenplan": {
        "name": "Alibaba Token Plan",
        "statusLink": "https://status.aliyun.com",
        "color": "#ff6a00"
    },
    "amp": {
        "name": "Amp",
        "dashboard": "https://ampcode.com/settings/usage",
        "color": "#dc2626"
    },
    "antigravity": {
        "name": "Antigravity",
        "statusLink": "https://www.google.com/appsstatus/dashboard/products/npdyhgECDJ6tB66MxXyo/history",
        "color": "#60ba7e"
    },
    "augment": {
        "name": "Augment",
        "dashboard": "https://app.augmentcode.com/account/subscription",
        "statusPage": "https://status.augmentcode.com",
        "color": "#6366f1",
        "statusFeed": {
            "kind": "statuspage",
            "base": "https://status.augmentcode.com"
        }
    },
    "azureopenai": {
        "name": "Azure OpenAI",
        "dashboard": "https://ai.azure.com",
        "statusLink": "https://azure.status.microsoft/en-us/status",
        "color": "#0078d4"
    },
    "bedrock": {
        "name": "AWS Bedrock",
        "dashboard": "https://console.aws.amazon.com/bedrock",
        "statusLink": "https://health.aws.amazon.com/health/status",
        "color": "#ff9900"
    },
    "chutes": {
        "name": "Chutes",
        "dashboard": "https://chutes.ai",
        "color": "#3184ff"
    },
    "claude": {
        "name": "Claude",
        "dashboard": "https://console.anthropic.com/settings/billing",
        "subscriptionDashboard": "https://claude.ai/settings/usage",
        "statusPage": "https://status.claude.com/",
        "color": "#cc7c5e",
        "statusFeed": {
            "kind": "statuspage",
            "base": "https://status.claude.com"
        },
        "statusScopes": [
            "Claude Code",
            "Claude API",
            "claude.ai",
            "Claude Console",
            "Everything"
        ]
    },
    "clawrouter": {
        "name": "ClawRouter",
        "dashboard": "https://clawrouter.openclaw.ai/dashboard/access",
        "color": "#596ef6"
    },
    "codebuff": {
        "name": "Codebuff",
        "dashboard": "https://www.codebuff.com/usage",
        "color": "#44ff00"
    },
    "codex": {
        "name": "Codex",
        "dashboard": "https://chatgpt.com/codex/settings/usage",
        "statusPage": "https://status.openai.com/",
        "color": "#49a3b0",
        "statusFeed": {
            "kind": "incidentio",
            "base": "https://status.openai.com/proxy/status.openai.com"
        },
        "statusScopes": [
            "Codex",
            "APIs",
            "ChatGPT",
            "Everything"
        ]
    },
    "commandcode": {
        "name": "Command Code",
        "dashboard": "https://commandcode.ai/studio",
        "subscriptionDashboard": "https://commandcode.ai/sixhobbits/settings/billing",
        "color": "#000000"
    },
    "copilot": {
        "name": "Copilot",
        "dashboard": "https://github.com/settings/copilot",
        "statusPage": "https://www.githubstatus.com/",
        "color": "#a855f7",
        "statusFeed": {
            "kind": "statuspage",
            "base": "https://www.githubstatus.com"
        }
    },
    "crof": {
        "name": "Crof",
        "dashboard": "https://crof.ai/dashboard",
        "color": "#2eab94"
    },
    "crossmodel": {
        "name": "CrossModel",
        "dashboard": "https://crossmodel.ai/console/usage",
        "color": "#7c3aed"
    },
    "cursor": {
        "name": "Cursor",
        "dashboard": "https://cursor.com/dashboard?tab=usage",
        "statusPage": "https://status.cursor.com",
        "color": "#00bfa5",
        "statusFeed": {
            "kind": "statuspage",
            "base": "https://status.cursor.com"
        }
    },
    "deepseek": {
        "name": "DeepSeek",
        "dashboard": "https://platform.deepseek.com/usage",
        "statusLink": "https://status.deepseek.com",
        "color": "#527df0"
    },
    "deepgram": {
        "name": "Deepgram",
        "dashboard": "https://console.deepgram.com/project/",
        "statusLink": "https://status.deepgram.com",
        "color": "#6467f2"
    },
    "devin": {
        "name": "Devin",
        "dashboard": "https://app.devin.ai",
        "subscriptionDashboard": "https://app.devin.ai/settings/usage",
        "color": "#46b482"
    },
    "doubao": {
        "name": "Doubao",
        "dashboard": "https://console.volcengine.com/ark/region:ark+cn-beijing/openManagement?LLM=%7B%7D&advancedActiveKey=subscribe",
        "color": "#3370ff"
    },
    "elevenlabs": {
        "name": "ElevenLabs",
        "dashboard": "https://elevenlabs.io/app/developers/usage",
        "subscriptionDashboard": "https://elevenlabs.io/app/subscription",
        "statusLink": "https://status.elevenlabs.io",
        "color": "#ebebe6"
    },
    "factory": {
        "name": "Droid",
        "dashboard": "https://app.factory.ai/settings/billing",
        "statusPage": "https://status.factory.ai",
        "color": "#ff6b35",
        "statusFeed": {
            "kind": "statuspage",
            "base": "https://status.factory.ai"
        }
    },
    "gemini": {
        "name": "Gemini",
        "dashboard": "https://gemini.google.com",
        "statusLink": "https://www.google.com/appsstatus/dashboard/products/npdyhgECDJ6tB66MxXyo/history",
        "color": "#ab87ea"
    },
    "grok": {
        "name": "Grok",
        "dashboard": "https://grok.com/?_s=usage",
        "statusLink": "https://status.x.ai",
        "color": "#10a37f"
    },
    "groq": {
        "name": "Groq",
        "dashboard": "https://console.groq.com/dashboard/metrics",
        "statusLink": "https://status.groq.com",
        "color": "#f56844"
    },
    "jetbrains": {
        "name": "JetBrains AI",
        "color": "#ff3399"
    },
    "kilo": {
        "name": "Kilo",
        "dashboard": "https://app.kilo.ai/usage",
        "color": "#f27027"
    },
    "kimi": {
        "name": "Kimi",
        "dashboard": "https://www.kimi.com/code/console",
        "color": "#fe603c"
    },
    "kimik2": {
        "name": "Kimi K2 (unofficial)",
        "dashboard": "https://kimrel.com/my-credits",
        "color": "#4c00ff"
    },
    "kiro": {
        "name": "Kiro",
        "dashboard": "https://app.kiro.dev/account/usage",
        "statusLink": "https://health.aws.amazon.com/health/status",
        "color": "#ff9900"
    },
    "llmproxy": {
        "name": "LLM Proxy",
        "color": "#24b47e"
    },
    "litellm": {
        "name": "LiteLLM",
        "color": "#4c89f0"
    },
    "manus": {
        "name": "Manus",
        "dashboard": "https://manus.im",
        "color": "#34322d"
    },
    "mimo": {
        "name": "Xiaomi MiMo",
        "dashboard": "https://platform.xiaomimimo.com/#/console/balance",
        "color": "#ff6900"
    },
    "minimax": {
        "name": "MiniMax",
        "dashboard": "https://platform.minimax.io/user-center/payment/coding-plan?cycle_type=3",
        "color": "#fe603c"
    },
    "mistral": {
        "name": "Mistral",
        "dashboard": "https://admin.mistral.ai/organization/usage",
        "statusLink": "https://status.mistral.ai",
        "color": "#ff500f"
    },
    "moonshot": {
        "name": "Moonshot / Kimi API",
        "dashboard": "https://platform.moonshot.ai/console/account",
        "color": "#205deb"
    },
    "ollama": {
        "name": "Ollama",
        "dashboard": "https://ollama.com/settings",
        "color": "#888888"
    },
    "openai": {
        "name": "OpenAI",
        "dashboard": "https://platform.openai.com/usage",
        "statusPage": "https://status.openai.com",
        "color": "#0f826e",
        "statusFeed": {
            "kind": "incidentio",
            "base": "https://status.openai.com/proxy/status.openai.com"
        }
    },
    "opencode": {
        "name": "OpenCode",
        "dashboard": "https://opencode.ai",
        "color": "#3b82f6"
    },
    "opencodego": {
        "name": "OpenCode Go",
        "dashboard": "https://opencode.ai",
        "color": "#3b82f6"
    },
    "openrouter": {
        "name": "OpenRouter",
        "dashboard": "https://openrouter.ai/settings/credits",
        "statusLink": "https://status.openrouter.ai",
        "color": "#6467f2"
    },
    "perplexity": {
        "name": "Perplexity",
        "dashboard": "https://www.perplexity.ai/account/usage",
        "statusLink": "https://status.perplexity.com/",
        "color": "#20b2aa"
    },
    "poe": {
        "name": "Poe",
        "dashboard": "https://poe.com/api/keys",
        "color": "#5d5cde"
    },
    "qoder": {
        "name": "Qoder",
        "color": "#10b981"
    },
    "sakana": {
        "name": "Sakana AI",
        "dashboard": "https://console.sakana.ai/billing",
        "color": "#2975db"
    },
    "stepfun": {
        "name": "StepFun",
        "dashboard": "https://platform.stepfun.com/plan-usage",
        "color": "#2196f2"
    },
    "sub2api": {
        "name": "sub2api",
        "color": "#2dc6d8"
    },
    "synthetic": {
        "name": "Synthetic",
        "color": "#141414"
    },
    "t3chat": {
        "name": "T3 Chat",
        "dashboard": "https://t3.chat/settings/customization",
        "subscriptionDashboard": "https://t3.chat/settings/subscription",
        "color": "#f56647"
    },
    "venice": {
        "name": "Venice",
        "dashboard": "https://venice.ai/settings/api",
        "color": "#3399ff"
    },
    "vertexai": {
        "name": "Vertex AI",
        "dashboard": "https://console.cloud.google.com/vertex-ai",
        "statusLink": "https://status.cloud.google.com",
        "color": "#4285f4"
    },
    "warp": {
        "name": "Warp",
        "dashboard": "https://docs.warp.dev/reference/cli/api-keys",
        "color": "#938bb4"
    },
    "wayfinder": {
        "name": "Wayfinder",
        "color": "#10a37f"
    },
    "windsurf": {
        "name": "Windsurf",
        "dashboard": "https://windsurf.com/subscription/usage",
        "color": "#34e8bb"
    },
    "zai": {
        "name": "z.ai",
        "color": "#e85a6a"
    },
    "zed": {
        "name": "Zed",
        "color": "#084eff"
    }
};
